title: Prasanthi Vanga
description: Data Engineer & Analyst
url: "https://pvanga2206.github.io"

# Use our custom layout, not a theme
layout: default

# Don't use any gem-based theme
theme: null

plugins: []
